LEAGUE = {1:
          {'SETTINGS': {'pss_cmp': 0.25,
                        'pss_inc': -0.25,
                        'pss_yds': 0.04,
                        'pss_td': 5,
                        'pss_int': -2,
                        'rsh_yds': 0.10,
                        'rsh_td': 6,
                        'rec_rec': 0.5,
                        'rec_yds': 0.10,
                        'rec_td': 6},
          'LINEUP_SLOTS': {'QB': 1,
                            'RB': 2,
                            'WR': 2,
                            'TE': 1,
                            'FLEX': 2},
          'TEAM_NAMES': {1: 'All Hail the IR Spot',
                          3: 'HeisenBerg',
                          4: 'Bourbons n Sacks',
                          5: 'Grndlesmooch',
                          6: "Makin' it rain",
                          7: 'Kamarica Industries',
                          8: 'Straight Cash Homey',
                          9: "Worley's Leotard",
                          10: 'YourenotwrongWalter',
                          11: '12th Man',
                          12: 'ABsLouisVSuitcase',
                          13: 'SpaceForce',
                          14: 'Pickle Rick',
                          15: 'Epstein was murdered'},
          'MY_TEAM': 4,
          'LOGIN': 'phi_phi_411@yahoo.com',
          'KEY': 'kentucky2@',
          'LEAGUE_ID': 624679},
          2:
          {'SETTINGS': {'pss_yds': 0.04,
                        'pss_td': 4,
                        'pss_int': -1,
                        'rsh_yds': 0.10,
                        'rsh_td': 6,
                        'rec_rec': 0.5,
                        'rec_yds': 0.10,
                        'rec_td': 6},
          'LINEUP_SLOTS': {'QB': 1,
                            'RB': 2,
                            'WR': 2,
                            'TE': 1,
                            'FLEX': 2},
          'TEAM_NAMES': {1: 'Putin Away',
                         2: 'copperheads',
                         3: 'PimpinSinceBeenPimpn',
                         4: 'Silver Hawk',
                         5: "It's Gonna Be HUGE",
                         6: 'Killer Katz',
                         7: 'I Have Andrews Luck',
                         8: 'Knights of the Keg',
                         9: 'Wentz Wagoneer',
                         10: 'Hammer Down'},
          'LOGIN': 'mworles40@yahoo.com',
          'KEY': 'kentucky2',
          'LEAGUE_ID': 1009392,
          'MY_TEAM': 3}
          }
